package ExceptionHandlingPractice;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class TryCatchPractice {

    public static void main(String[] args) throws Exception {

        int x=3;
        int y=0;

          throw new Exception("this exception is created by me");

    }
}
